### ISSUE TITLE
Further improvements on DCB part of the documentation

### ISSUE THREAD

**Issue by wcparker** [ypsun-umd/gbtx_communication_doc#8]
Your documentation is excellent, very clear and thorough!  Could you please add just a couple things:

- [x] Directions to power up the DCB without a backplane
- [x] The fact that the I2C SDA/SCL needs to be cross-jumped.  I guess we will ship the boards that way anyway, but it's best for everyone to understand what's going on.
- [x] I see that you've started to do this, but in the long term it's useful to add a troubleshooting section of common problems we have encountered and solved.

Thanks!

**Comment by ypsun-umd** [comment]
@wcparker I finished all 3 requirements. Please take another look.

**Comment by ypsun-umd** [comment]
I have also released both GBTx DB and DCB schematics. Hopefully Tom won't kill me for this.

**Comment by ypsun-umd** [comment]
@wcparker You can always give other people this link:
https://github.com/ypsun-umd/gbtx_communication_doc/releases/latest
It always points to the latest release.

**Comment by wcparker** [comment]
Nice, thanks.

Will
